# Generated by Django 6.1 on 2026-08-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_utilisateur_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
