# Generated by Django 6.1 on 2026-08-21 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hopital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Examen médical',
                'verbose_name_plural': 'Examens médicaux',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='HopitalExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hopitaux', to='examen.examenmedical')),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='hopital.hopital')),
            ],
            options={
                'verbose_name': 'Association hôpital-examen',
                'verbose_name_plural': 'Associations hôpital-examen',
                'unique_together': {('hopital', 'examen')},
            },
        ),
    ]
