# Generated by Django 6.1 on 2026-08-21 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hopital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateauTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Plateau technique',
                'verbose_name_plural': 'Plateaux techniques',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='HopitalPlateauTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plateaux_techniques', to='hopital.hopital')),
                ('plateau_technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hopitaux', to='plateau.plateautechnique')),
            ],
            options={
                'verbose_name': 'Association hôpital-plateau technique',
                'verbose_name_plural': 'Associations hôpital-plateau technique',
                'unique_together': {('hopital', 'plateau_technique')},
            },
        ),
    ]
