# Generated by Django 6.1 on 2026-08-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeHopital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': "Type d'hôpital",
                'verbose_name_plural': "Types d'hôpitaux",
                'ordering': ['nom'],
            },
        ),
    ]
