# Generated by Django 6.1 on 2026-08-21 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0002_alter_hopital_latitude_alter_hopital_longitude'),
        ('maladie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriseEnCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prises_en_charge', to='hopital.hopital')),
                ('maladie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prises_en_charge', to='maladie.maladie')),
            ],
            options={
                'verbose_name': 'Prise en charge',
                'verbose_name_plural': 'Prises en charge',
                'unique_together': {('hopital', 'maladie')},
            },
        ),
    ]
